### ISSUE TITLE
Compilation fails on Debian 11 with ocaml 4.11.1

### ISSUE THREAD

**Issue by nettrino** [kupl/VeriSmart-public#1]
Got the following error on Debian 11 - probably easy to resolve but pasting it here in case you want to update your install instructions in future commits
```+ ocamlfind ocamldep -package batteries -package str -package Z3 -package yojson -package ocamlgraph -modules src/main.ml > src/main.ml.depends
ocamlfind: Package `batteries' not found
Command exited with code 2.
```

**Comment by SunBeomSo** [comment]
Hi @nettrino ,

Could you double-check if you have ran the command mentioned in readme?
```
opam install -y conf-m4.1 ocamlfind ocamlbuild num yojson batteries ocamlgraph zarith
```

Error messages that state ``Package ... not found `` could happen if some related packages are not installed via ``opam install`` command. I think such errors are not related to OS versions.

**Comment by nettrino** [comment]
Yep I had run this command - I switched versions using `opam switch create ocaml-base-compiler.4.07.1` and things worked out for this step

**Comment by nettrino** [comment]
Reopening this a I am running to another issue both on Debian 11 as well as on OS X. After having installed the dependencies  I get 
```
+ ocamlfind ocamldep -package batteries -package str -package Z3 -package yojson -package ocamlgraph -modules src/main.ml > src/main.ml.depends
ocamlfind: Package `Z3' not found
```
though I haven installed Z3 with the `--ml` flag. 

Any chance this could be made available as a dockerized app or that you could verify the steps from a vanilla install in a fresh Linux VM?

**Comment by SunBeomSo** [comment]
Hi @nettrino,

I have previously tried and confirmed that the instructions successfully work in different machines, different versions of OS (including several versions of OS X and Ubuntu, but not Debian), and different versions of OCaml (including OCaml v. 4.11.1).

I guess you missed some steps in installing Z3 and binding it with OCaml. For example, suppose you installed Z3 and bound it on OCaml version A. Then, if you are working on OCaml version B, you have to separately install Z3 bind it with OCaml version B.

If Z3 is successfully bound in some versions of OCaml, for example 4.11.1, then you could see a directory ``~/.opam/4.11.1/lib/Z3`` exists.

**Comment by nettrino** [comment]
I did not have ocaml installed in my OS X (12.2.1) so this was a fresh installation and needed gmp to be built manually due to missing dependencies for zarith, so I figured there might be additional corner cases like this as systems evolve, which is why I recommended the Docker path - I will try and make a CR with a Dockerfile to make it a bit easier to get a reproducable build.
