### ISSUE TITLE
Conflict issues with ocmal versions

### ISSUE THREAD

**Issue by xiaoguaishouaaa** [kupl/VeriSmart-public#11]
Hello, when configuring the running environment, there is a conflict problem of OCMAL version, as shown in the figure below.
![verismart01](https://user-images.githubusercontent.com/114983861/201247713-b1c5c99a-8469-4766-af65-89eb1b0d9927.png)

**Comment by xiaoguaishouaaa** [comment]
> Hi, can you provide more specific information to diagnose the problem? What command did you run? What are the versions of your OCaml and opam? (check them via `ocaml --version` and `opam --version`)

Thank you for your reply. I got the following error when I ran the ./build command in the Build section:
ocamlfind: Package `batteries' not found
Command exited with code 2.
After searching, I found a version conflict about ocmal.
My version of OCMAL ：4.05.0
My version of OPAM：1.2.2

**Comment by SunBeomSo** [comment]
The problem may be because you are using a too old version of opam. Please try the following instructions and let me know the progress.
* Remove your old opam (its location can be identified by ``which opam``).
* Reinstall the recent version of opam by referring to this page: https://opam.ocaml.org/doc/Install.html
* Check that the version of your opam is now > 2.0.0 (via ``opam --version``).
* Reinstall OCaml libs mentioned in the readme, and rerun ``./build``.

**Comment by xiaoguaishouaaa** [comment]
> The problem may be because you are using a too old version of opam. Please try the following instructions and let me know the progress.
> 
> * Remove your old opam (its location can be identified by `which opam`).
> * Reinstall the recent version of opam by referring to this page: https://opam.ocaml.org/doc/Install.html
> * Check that the version of your opam is now > 2.0.0 (via `opam --version`).
> * Reinstall OCaml libs mentioned in the readme, and rerun `./build`.

Thanks for your reply, I did as you said, installed opam> 2.0.0 and executed "opam install -y conf-m4.1 ocamlfind ocamlbuild num yojson batteries ocamlgraph zarith", after executing ./build again, I got the following error:
 ./build: line 21: ocamlbuild: command not found.
I made sure that ocamlbuild is already installed.

**Comment by xiaoguaishouaaa** [comment]
> The problem may be because you are using a too old version of opam. Please try the following instructions and let me know the progress.
> 
> * Remove your old opam (its location can be identified by `which opam`).
> * Reinstall the recent version of opam by referring to this page: https://opam.ocaml.org/doc/Install.html
> * Check that the version of your opam is now > 2.0.0 (via `opam --version`).
> * Reinstall OCaml libs mentioned in the readme, and rerun `./build`.

Thanks for your reply, I did as you said, installed opam> 2.0.0 and executed "opam install -y conf-m4.1 ocamlfind ocamlbuild num yojson batteries ocamlgraph zarith", after executing ./build , I got the following error:
+ ocamlfind ocamldep -package batteries -package str -package Z3 -package yojson -package ocamlgraph -modules src/main.ml > src/main.ml.depends
ocamlfind: Package `batteries' not found
Command exited with code 2.
Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.

**Comment by SunBeomSo** [comment]
Based on the error message ``ocamlfind: Package `batteries' not found``, it seems that ``ocamlfind`` or ``batteries`` are not installed properly.

* Could you check whether ``batteries`` is installed or not (via ``opam list``)?
* Please reinstall ``ocamlfind`` following the instruction at: https://stackoverflow.com/questions/30584028/ocamlfind-command-not-found/55371188#55371188. After that, please try reinstalling OCamll libs in the readme.

* Also, I would like to ask if you saw any error messages while running the command ``opam install -y conf-m4.1 ocamlfind ocamlbuild num yojson batteries ocamlgraph zarith``.

**Comment by sunbeomso** [comment]
Please reopen this issue if the above answer does not resolve the trouble.
