### ISSUE TITLE
undefined symbol: Z3_fixedpoint_pop

### ISSUE THREAD

**Issue by whbjzzwjxq** [kupl/VeriSmart-public#14]
Ocaml version: 4.08.1
Os version: Ubuntu 18.03
opam version: 2.0.5

After compilation, run `./main.native --help`
Terminal: 
`./main.native: symbol lookup error: ./main.native: undefined symbol: Z3_fixedpoint_pop`

Thanks for your open-source codebase, but I have some trouble with using it.

**Comment by sunbeomso** [comment]
Hi @whbjzzwjxq,

The error messages that contain ``undefined symbol`` may be issues related to Z3 installation.

Could you try a clean build following the suggestion in the below?
https://github.com/Z3Prover/z3/issues/1804

**Comment by sunbeomso** [comment]
Close due to inactivity
