### ISSUE TITLE
Environment configuration issues

### ISSUE THREAD

**Issue by lomos237** [kupl/VeriSmart-public#15]
When configuring the environment, after entering "./build", the error message shows ocamlfind: Package `Z3' not found. But I have successfully installed the Z3 library and can use the command to view the Z3 version: Z3 version 4.12.2 - 64 bit

**Comment by shikahJS** [comment]
I got the same error, did you manage to fix it?

**Comment by sunbeomso** [comment]
As mentioned in README, during Z3 installation, you should provide ``--ml`` option for OCaml binding. Please reopen this issue when there are still some problems.
