### ISSUE TITLE
Assertion fails in OS X 

### ISSUE THREAD

**Issue by echohermion** [kupl/VeriSmart-public#3]
Got the following error on OS X with a contract that imports external solidity files:

`File "src/util/solc.ml", line 34, characters 11-17: Assertion failed
Raised at Yojson.json_error in file "common.ml", line 5, characters 19-39
Called from Yojson.Basic.from_lexbuf in file "lib/read.mll", line 1113, characters 6-21
Called from Yojson.Basic.from_channel in file "lib/read.mll", line 1130, characters 6-26
Called from Solc.get_json_ast in file "src/util/solc.ml", line 27, characters 15-44`

The contract begins with:
`import "./Token.sol"; 
import "./Utils.sol"; 
import "./lib/ECVerify.sol"; 
import "./SecretRegistry.sol";`

And all import files are well-organized in the same folder. 

Seems that the error only occurs for contracts that import external files while works well for contracts without import files.

**Comment by SunBeomSo** [comment]
Hi @echohermion ,

In the current implementation, VeriSmart takes source code where all imports are merged into one file, e.g., using solidity-flattener: https://github.com/poanetwork/solidity-flattener

So, please provide VeriSmart with a merged source code when using it.
