### ISSUE TITLE
Error in solc running ./main.native

### ISSUE THREAD

**Issue by jcrreis** [kupl/VeriSmart-public#9]
Hello,

I installed this project and i'm trying to run a contract that I have built that replicates basic functionality of a Wallet. However i'm getting the following error.

When i run:

```
./main.native -input Wallet.sol -solv 0.8.7
```

I get this:

```
./main.native -input Wallet.sol -solv 0.8.7 
[CHECKER] Integer Over/Underflows
[CHECKER] Division-by-zero
[CHECKER] Suicidal
[CHECKER] Ether-Leaking

Solc.CompilationError
Raised at Stdlib.input_line.scan in file "stdlib.ml", line 449, characters 14-31
Called from Solc.get_json_ast' in file "src/util/solc.ml", line 29, characters 21-37

```

Can you help me ?

Thanks.

**Comment by shiftshapes** [comment]
I am experiencing the same issue. Any fix?

**Comment by shiftshapes** [comment]
> Hello,
> 
> I installed this project and i'm trying to run a contract that I have built that replicates basic functionality of a Wallet. However i'm getting the following error.
> 
> When i run:
> 
> ```
> ./main.native -input Wallet.sol -solv 0.8.7
> ```
> 
> I get this:
> 
> ```
> ./main.native -input Wallet.sol -solv 0.8.7 
> [CHECKER] Integer Over/Underflows
> [CHECKER] Division-by-zero
> [CHECKER] Suicidal
> [CHECKER] Ether-Leaking
> 
> Solc.CompilationError
> Raised at Stdlib.input_line.scan in file "stdlib.ml", line 449, characters 14-31
> Called from Solc.get_json_ast' in file "src/util/solc.ml", line 29, characters 21-37
> ```
> 
> Can you help me ?
> 
> Thanks.

If you don't already have 'pragma solidity 0.8.7;' in your contract try inserting that and it should run without any issue. It worked for me.

**Comment by SunBeomSo** [comment]
Please make sure that you installed the solc binary named ``solc_0.8.7``, as explained in the readme. Also, your input source code should be compiled by that solc.

If this answer does not work, please reopen this issue. When you reopen the issue, to diagnose the problem concretely, please provide a source code that can reproduce the problem.
